### ISSUE TITLE
The table does not exist: {{%active_record}}

### ISSUE THREAD

**Issue by wojtasCK** [yiisoft/yii2-gii#190] opened 2016-08-31 13:33 UTC
### What steps will reproduce the problem?
Generate model of existing table
### What's expected?
Generated preview
### What do you get instead?
The table does not exist: {{%active_record}}

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev-master (reference e39fc74d9ad82751e2c0e8a0b1329202f61d91b0)
| Gii version      | dev-master (reference 09243fe7fa0d379b842ef3e9582988d9cf8f659b)
| PHP version      | 7.0.10
| Operating system | Linux Xubuntu 14.04

**Comment by samdark** [comment] 2016-08-31 13:49
1. Was it OK before? When?
2. Are you sure you're using correct connection?

**Comment by wojtasCK** [comment] 2016-08-31 15:06
When i change version to 2.0.5 in composer.json, it's all ok.

**Comment by samdark** [comment] 2016-08-31 15:47
OK. Is it MySQL? Could you provide a table schema for your table and make a screenshot of the form so I know how it's filled when erroring?

**Comment by wojtasCK** [comment] 2016-09-01 06:25
It's postgresql. 
 
[Schema](http://pastebin.com/NKe4WYdW)

[Form](http://pasteboard.co/fyLPCISbq.png)

**Comment by athl64** [comment] 2016-09-02 12:23
confirm issue.
With PostgreSQL - same exception appears.
With MySQL - preview successfully generating but there are no relations created in model.

**Comment by samdark** [comment] 2016-09-02 13:44
:( @athl64 do want to attempt solving it?

**Comment by athl64** [comment] 2016-09-02 15:46
@samdark  I will create pull request if i'll find a solution.

**Comment by klimov-paul** [comment] 2016-09-05 08:59
Issue confirmed.

**Comment by klimov-paul** [comment] 2016-09-05 09:08
It is caused by recent fix of main repo issue: https://github.com/yiisoft/yii2/issues/9561

Exception thrown by `yii\gii\generators\model\Generator::generateRelationName()` during the invocation of `ActiveRecord::hasProperty()`.

**Comment by klimov-paul** [comment] 2016-09-05 09:23
Issue resolved by commit:
https://github.com/yiisoft/yii2/commit/ea03f56d42e6aa7b9b70b8a22d65d54d903e870d

Please update main yii2 repo in order to make issue dissappear.

**Closed by klimov-paul** 2016-09-05 09:23 UTC
Labels: bug

**Comment by anildsvv14** [comment] 2017-08-25 07:39
I am new to yii and learing generating the CRUD operation through gii first i create a country table and generate the model and controller and views using gii i am get following error 
**Invalid Configuration – yii\base\InvalidConfigException The table does not exist: {{%country_search}}**

**Comment by tepaleguiojo** [comment] 2018-01-27 19:40
Hi,

Please help me on my error. 

I'm trying to run `gii/model` to generate all my models. I also extended the ActiveRecord class, `class ExtendedActiveRecord extends yii\db\ActiveRecord { ... }`, to implement default behaviors of the generated models .

**Command Line Script**
 `php yii gii/model --tableName=* --ns=api\modules\v1\models --baseClass=api\modules\v1\base\AppBaseActiveRecord`

**Error Message** (after running the script)
`Exception 'yii\base\InvalidConfigException' with message 'The table does not exist: {{%app_base_active_record}}'`

**Additional Info**
- OS: Windows 7 Ultimate 64bit
- PHP: 5.6.31
- Yii version: 2.0.13.1
- Gii version: 2.0.6 

By the way, the script I used in MacOS works perfectly.

**Comment by wtfmrpresident** [comment] 2018-01-28 20:12
I have the same problem now..
If I check some attribute in AR then Gii throw exception:
The table does not exist: {{%active_record}}

But before I did't saw this problem

Yii2 advanced was downloaded today

**Comment by Mikecoon** [comment] 2019-01-31 13:49
Any solution so far?

**Comment by sizeg** [comment] 2019-01-31 13:55
@Mikecoon 
```php
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();

        // Gii fix
        try {
            $hasCreatedAt = $this->hasAttribute('created_at');
            $hasUpdatedAt = $this->hasAttribute('updated_at');
        } catch (\yii\base\InvalidConfigException $e) {
            $hasCreatedAt = false;
            $hasUpdatedAt = false;
        }
        if ($hasCreatedAt || $hasUpdatedAt) {
            $attributes = [];
            if ($hasCreatedAt) {
                $attributes[BaseActiveRecord::EVENT_BEFORE_INSERT][] = 'created_at';
            }
            if ($hasUpdatedAt) {
                $attributes[BaseActiveRecord::EVENT_BEFORE_INSERT][] = 'updated_at';
                $attributes[BaseActiveRecord::EVENT_BEFORE_UPDATE][] = 'updated_at';
            }
            $behaviors['timestamp'] = [
                'class' => TimestampBehavior::class,
                'value' => new Expression('NOW()'),
                'attributes' => $attributes,
            ];
        }

        return $behaviors;
    }
```

**Comment by Veitor** [comment] 2023-03-10 09:37
The better solution I think is to remove `setAttributes([])` call on base ActiveRecord which will trigger database schema query using error table name.

The code snippet is here: https://github.com/yiisoft/yii2-gii/blob/26afd5c3585e715dfca2d1c5cd88c0ebad5dcacf/src/generators/model/Generator.php#L902

This line of code doesn't make sense and instead causes problems
