### ISSUE TITLE
Bad url in preview of the generated file

### ISSUE THREAD

**Issue by oshh** [yiisoft/yii2-gii#245] opened 2017-02-01 22:59 UTC
### What steps will reproduce the problem?
I am following the steps of 
http://www.yiiframework.com/doc-2.0/guide-start-gii.html

Model Generator => Preview => click on name of generated file
OR
Model Generator => Preview => click on "diff" Button

### What do you get instead?
Bad Request (#400): Missing required parameters: file

### Additional info
I noticed the link being bad :
`index.php?r=gii%2Fdefault%2Fpreview&id=model&amp;file=74e8f2c0aafe9daa499b0f31523a55d6`

So I opened in a new tab 
`index.php?r=gii%2Fdefault%2Fpreview&id=model&file=74e8f2c0aafe9daa499b0f31523a55d6`

Now I get: "Code file not found: 74e8f2c0aafe9daa499b0f31523a55d6" 

I just started to use YII today, so sorry I can not provide a lot of usefull info.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      |
| Operating system |

**Comment by samdark** [comment] 2017-02-02 13:43
What's the version of the gii extension?

**Comment by oshh** [comment] 2017-02-02 13:47
How can I find out?

**Comment by oshh** [comment] 2017-02-02 13:49
Found
"2.0.5 March 18, 2016" in the changelog

**Comment by samdark** [comment] 2017-02-02 17:33
Hmm. I've tried to reproduce that but failed. What's the database used? What is table schema?

**Comment by oshh** [comment] 2017-02-02 18:46
MySql 

CREATE TABLE country (
  code char(2) NOT NULL,
  name char(52) NOT NULL,
  population int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by oshh** [comment] 2017-02-02 18:50
![bildschirmfoto 2017-02-02 um 19 48 07](https://cloud.githubusercontent.com/assets/6878255/22563431/cf2b213c-e980-11e6-9600-548cfeb13b53.png)

**Comment by samdark** [comment] 2017-02-02 18:51
What's your web server and what's the config file for the host you're using?

**Comment by oshh** [comment] 2017-02-02 18:54
[SERVER_SOFTWARE] => Apache

Which config file do you mean?
This is a standard web hosting (virtual server) so I have no access to low-level stuff ...

**Comment by oshh** [comment] 2017-02-02 19:03
update:
When I correct the bad "&amp;" directly in the href= (via Firebug) then the file gets shown. The error about the missing file seems to be related to opening the link in a new tab.

**Comment by samdark** [comment] 2017-02-02 19:06
Yes. The issue isn't really about Gii but about request data and URLs generation with your config of Apache. Since we don't have config to reproduce it, I don't think we can fix it.

**Comment by oshh** [comment] 2017-02-02 19:08
But that link target does not get produced by Apache, does it? 
After clicking "Preview", how can Apache be involved in the generated content of a `<a href="...">` ?

**Comment by samdark** [comment] 2017-02-02 19:11
Apache passes request data to PHP. This data is parsed and used by Yii for request handling and URLs.

**Comment by oshh** [comment] 2017-02-02 19:16
When I start the Model Generator, I get to this URL:
/index.php?r=gii%2Fdefault%2Fview&id=model
strangely, here we have the correct "&" between "view" and "id"
So this does get "produced" not by passing request data?

**Comment by samdark** [comment] 2017-02-02 20:21
No, it's generated using the same way: https://github.com/yiisoft/yii2-gii/blob/master/views/default/view/files.php#L68

**Comment by oshh** [comment] 2017-02-03 09:26
Well, I personally can live with altering the link through Firebug. Thank you for your support.

**Comment by samdark** [comment] 2017-02-03 09:38
OK. Closing the issue then since it's hardly possible to find out a reason w/o me reproducing it.

**Comment by nirleka** [comment] 2017-02-20 06:13
I also get this error.
The generated preview file url is: `gii/default/preview?id=model&amp;file=c9fc636c6f26c251bf10f6a3d36b2e62`

Testing on other view also get this error.
```php
<?= Html::a(Html::encode('testing.html'), 
        ['preview', 'id' => '1', 'test'=>'asdasda', 'file' => 'asdasdasdasqrqwr'], 
        ['class' => 'preview-code', 'data-title' => 'testing.html']) 
    ?>
```
Generated url: `http://localhost/supervisi-akademik/www/site/preview/1?test=asdasda&amp;file=asdasdasdasqrqwr`

* Server Configuration: Apache/2.4.10 (Win32) - PHP/5.5.15
* Gii version: 2.0.5 March 18, 2016
* The server is bundled by Xampp version 5.6.8

But, testing on other server with PHP Version 5.5.38 generated the correct url. Maybe it is related with PHP version. I will stick to newer PHP version.

**Comment by cebe** [comment] 2017-02-20 08:33
related reports:
- http://php.net/manual/en/function.http-build-query.php#102324
- http://php.net/manual/en/function.http-build-query.php#96692

Could possibly be fixed by passing the paremeters to `http_build_query()` explicitly in UrlManager and UrlRule.

**Comment by woese-dev** [comment] 2017-05-03 14:21
Hi,
I had the same problem with this topic and found that it was a wrong rule in the .htaccess file.
I had the following:
`RewriteRule .* /index.php?s=%1 [L]`
And the correct one, for the view to function in the GII, is:
`RewriteRule . index.php`

**Comment by samdark** [comment] 2017-12-22 20:51
Configuring webserver is described well in the guide so closing it.

**Closed by samdark** 2017-12-22 20:51 UTC
Labels: type:bug
