### ISSUE TITLE
Problems with typeahead.js / new release

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2-gii#40] opened 2015-05-19 05:18 UTC
I just created this issue about `typeahead.js` (https://github.com/yiisoft/yii2-gii/issues/38, https://github.com/yiisoft/yii2-gii/pull/39)
- https://github.com/francoispluchino/composer-asset-plugin/issues/115

Btw, we're experiencing some issues with the latest updates in gii...

*reading changelogs*

Did someone notice this?

https://github.com/twitter/typeahead.js/blob/master/CHANGELOG.md

> 0.11.0 April 25, 2015

> An overhaul of typeahead.js – consider this a release candidate for v1. There are bunch of API changes with this release so don't expect backwards compatibility with previous versions. There are also many new undocumented features that have been introduced. Documentation for those features will be added before v1 ships.

> Beware that since this release is pretty much a rewrite, there are bound to be some bugs. To be safe, you should consider this release beta software and throughly test your integration of it before using it in production environments. This caveat only applies to this release as subsequent releases will address any issues that come up.

This would explain several issues we have, but I'll need to investigate this further.

@qiangxue @samdark @cebe @klimov-paul 
If this is not an issue, it would be nice to have a patch release `2.0.5`.

If the typeahead.js changes are affecting gii, I've the feeling that  this could lead into some weird to find problems, and would therefore strongly recommend `2.1.0`(!).

**Comment by razvanphp** [comment] 2015-08-23 12:03
My pull request made it compatible with both old and new typeahead version. The only difference from gii point of view is the CSS class name, and for this I kept backwards compatibility.

@samdark can you please create a new release for yii2-gii that includes my PR? The framework is already at 2.0.6.

**Comment by samdark** [comment] 2015-08-24 10:47
@razvanphp there are still things to check before releasing it. Just fixed a regression.

Closing the issue since this one is fixed...

**Closed by samdark** 2015-08-24 10:47 UTC
